#!/bin/sh
set -x

for z in 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
do(
cd Z${z}
#   collecting files


cp ../odd2.c rcsf.inp
#   The angular data such as spin-angular coefficients are computed here.
rangular  <<S4
y
S4

#  Get initial estimates of wave functions using Thomas-Fermi potential.
rwfnestimate <<S5
y
2
*
S5

# Perform self-consistent field calculations
#   The spin-orbital equations are solved iteratively on the radial grid by a
#   finite diffrerence self-consistent field (SCF) procedure. Hamiltonian matrix
#   is constructed using the initial estimates of the radial functions and 
#   diagonalized to give expansion coefficients fo the CSFs for each of the ASF.
#   Improved estimates of radial functions are then obtained using the obtained
#   wave function estimates. This is repeated until the energy of the states or the 
#   do not change anymore.
rmcdhf > outodd_rmcdhf_initial <<S6
y
1-2
1-4
1
5
*
*
100
S6

#  Save the result to odd2
rsave odd2

# 3. For n=3, Get initial estimates for even

cp ../even2.c rcsf.inp
rangular  <<S4
y
S4

#  Get initial estimates of wave functions
rwfnestimate <<S5
y
2
*
S5

# Perform self-consistent field calculations
rmcdhf > outeven_rmcdhf_initial <<S6
y
1-3
1-3
1-2
5
*
*
100
S6

#  Save the result to even2
rsave even2

cd ..
   )
   done